CREATE TABLE users (
  id TEXT PRIMARY KEY,
  telegram_id TEXT UNIQUE,
  display_name TEXT NOT NULL,
  telegram_username TEXT,
  first_name TEXT,
  last_name TEXT,
  language_code TEXT,
  photo_url TEXT,
  is_premium INTEGER NOT NULL DEFAULT 0,
  referral_code TEXT UNIQUE,
  timezone TEXT NOT NULL DEFAULT 'Asia/Bangkok',
  trial_started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE courses (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  summary TEXT NOT NULL,
  daily_minutes INTEGER NOT NULL,
  duration_days INTEGER NOT NULL DEFAULT 60,
  accent TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  course_id TEXT NOT NULL REFERENCES courses(id),
  current_day INTEGER NOT NULL DEFAULT 1,
  active INTEGER NOT NULL DEFAULT 1,
  started_on TEXT NOT NULL DEFAULT CURRENT_DATE::text,
  enrolled_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  paused_at TEXT,
  UNIQUE(user_id, course_id)
);
CREATE INDEX enrollments_user_active_idx ON enrollments(user_id, active);

CREATE TABLE lessons (
  id TEXT PRIMARY KEY,
  course_id TEXT NOT NULL REFERENCES courses(id),
  day INTEGER NOT NULL,
  level INTEGER NOT NULL,
  round INTEGER NOT NULL,
  title TEXT NOT NULL,
  objective TEXT NOT NULL,
  content TEXT NOT NULL,
  practice_prompt TEXT NOT NULL,
  criteria_json TEXT NOT NULL DEFAULT '[]',
  estimated_minutes INTEGER NOT NULL DEFAULT 18,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  UNIQUE(course_id, day)
);
CREATE INDEX lessons_course_idx ON lessons(course_id);

CREATE TABLE reminder_templates (
  id TEXT PRIMARY KEY,
  level INTEGER NOT NULL,
  content TEXT NOT NULL,
  button_text TEXT NOT NULL,
  weight INTEGER NOT NULL DEFAULT 100,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  enrollment_id INTEGER NOT NULL REFERENCES enrollments(id),
  lesson_id TEXT NOT NULL REFERENCES lessons(id),
  original_answer TEXT NOT NULL,
  revised_answer TEXT,
  status TEXT NOT NULL DEFAULT 'submitted',
  rule_score REAL NOT NULL DEFAULT 0,
  rule_feedback TEXT NOT NULL DEFAULT '',
  ai_feedback TEXT,
  completion_source TEXT NOT NULL DEFAULT 'self',
  completed_on TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  UNIQUE(user_id, lesson_id)
);
CREATE INDEX submissions_user_idx ON submissions(user_id);

CREATE TABLE notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  lesson_id TEXT REFERENCES lessons(id),
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX notes_user_created_idx ON notes(user_id, created_at);

CREATE TABLE reminder_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  template_id TEXT NOT NULL REFERENCES reminder_templates(id),
  level INTEGER NOT NULL,
  sent_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  clicked_at TEXT,
  completed_at TEXT
);
CREATE INDEX reminder_events_user_sent_idx ON reminder_events(user_id, sent_at);

CREATE TABLE invitations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inviter_user_id TEXT NOT NULL REFERENCES users(id),
  invited_user_id TEXT NOT NULL REFERENCES users(id),
  invite_code TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  qualified_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  UNIQUE(invited_user_id)
);
CREATE INDEX invitations_inviter_status_idx ON invitations(inviter_user_id, status);

CREATE TABLE subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  plan_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  source TEXT NOT NULL,
  starts_at TEXT NOT NULL,
  ends_at TEXT NOT NULL,
  external_ref TEXT UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX subscriptions_user_status_end_idx ON subscriptions(user_id, status, ends_at);

CREATE TABLE payment_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  plan_key TEXT NOT NULL,
  invoice_payload TEXT NOT NULL UNIQUE,
  amount_stars INTEGER NOT NULL,
  recurring INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX payment_orders_user_status_idx ON payment_orders(user_id, status);

CREATE TABLE payment_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES payment_orders(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  telegram_payment_charge_id TEXT NOT NULL UNIQUE,
  provider_payment_charge_id TEXT,
  currency TEXT NOT NULL DEFAULT 'XTR',
  amount_stars INTEGER NOT NULL,
  subscription_expiration_date INTEGER,
  status TEXT NOT NULL DEFAULT 'paid',
  paid_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  refunded_at TEXT
);
CREATE INDEX payment_transactions_user_paid_idx ON payment_transactions(user_id, paid_at);

CREATE TABLE schema_version (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
