CREATE TABLE IF NOT EXISTS feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  category TEXT NOT NULL,
  content TEXT NOT NULL,
  page_context TEXT,
  app_version TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS feedback_status_created_idx
  ON feedback(status, created_at DESC);
CREATE INDEX IF NOT EXISTS feedback_user_created_idx
  ON feedback(user_id, created_at DESC);
