CREATE TABLE IF NOT EXISTS campaign_rewards (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  reward_mode TEXT NOT NULL DEFAULT 'discount',
  main_offer_type TEXT NOT NULL DEFAULT 'campaign',
  stackable_with_credits BOOLEAN NOT NULL DEFAULT false,
  budget_cap_minor BIGINT,
  start_at TEXT NOT NULL,
  end_at TEXT NOT NULL,
  eligibility_rule_json TEXT NOT NULL DEFAULT '{}',
  settlement_rule_version TEXT NOT NULL DEFAULT 'v1',
  created_by TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS campaign_rewards_status_window_idx
  ON campaign_rewards(status, start_at, end_at);
CREATE INDEX IF NOT EXISTS campaign_rewards_end_at_idx
  ON campaign_rewards(end_at);

CREATE TABLE IF NOT EXISTS order_pricing_snapshots (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  plan_key TEXT NOT NULL,
  currency TEXT NOT NULL,
  original_amount_minor BIGINT NOT NULL,
  main_offer_type TEXT NOT NULL DEFAULT 'none',
  main_offer_id TEXT,
  main_discount_amount_minor BIGINT NOT NULL DEFAULT 0,
  credits_redeemed_points BIGINT NOT NULL DEFAULT 0,
  credits_redeemed_amount_minor BIGINT NOT NULL DEFAULT 0,
  final_payable_amount_minor BIGINT NOT NULL,
  anchor_rate_version TEXT NOT NULL,
  pricing_rule_version TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'preview',
  idempotency_key TEXT UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS order_pricing_snapshots_user_created_idx
  ON order_pricing_snapshots(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS order_pricing_snapshots_status_created_idx
  ON order_pricing_snapshots(status, created_at DESC);

CREATE TABLE IF NOT EXISTS credits_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  entry_type TEXT NOT NULL,
  reward_type TEXT NOT NULL,
  amount_points BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'posted',
  business_key TEXT NOT NULL UNIQUE,
  related_order_id BIGINT REFERENCES payment_orders(id),
  related_invitation_id BIGINT REFERENCES invitations(id),
  related_campaign_reward_id TEXT REFERENCES campaign_rewards(id),
  expires_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS credits_ledger_user_created_idx
  ON credits_ledger(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS credits_ledger_user_status_expires_idx
  ON credits_ledger(user_id, status, expires_at);
