CREATE TABLE IF NOT EXISTS ability_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  course_id TEXT NOT NULL REFERENCES courses(id),
  stage_key TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT 'v1',
  prompt TEXT NOT NULL,
  rubric_json TEXT NOT NULL DEFAULT '[]',
  original_answer TEXT NOT NULL,
  revised_answer TEXT,
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'submitted',
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE UNIQUE INDEX IF NOT EXISTS ability_assessments_user_course_stage_unique
  ON ability_assessments(user_id, course_id, stage_key);

CREATE INDEX IF NOT EXISTS ability_assessments_user_created_idx
  ON ability_assessments(user_id, created_at DESC);
