CREATE TABLE IF NOT EXISTS review_queue_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  source_type TEXT NOT NULL,
  source_ref TEXT NOT NULL,
  course_id TEXT REFERENCES courses(id),
  lesson_id TEXT REFERENCES lessons(id),
  assessment_stage_key TEXT,
  reason TEXT NOT NULL,
  title TEXT NOT NULL,
  recommendation TEXT NOT NULL,
  due_on TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  resolved_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE UNIQUE INDEX IF NOT EXISTS review_queue_items_user_source_unique
  ON review_queue_items(user_id, source_type, source_ref, reason);

CREATE INDEX IF NOT EXISTS review_queue_items_user_status_due_idx
  ON review_queue_items(user_id, status, due_on);
