CREATE TABLE IF NOT EXISTS evidence_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  evidence_type TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_ref TEXT NOT NULL,
  course_id TEXT REFERENCES courses(id),
  lesson_id TEXT REFERENCES lessons(id),
  assessment_stage_key TEXT,
  source_version TEXT NOT NULL DEFAULT 'v1',
  status TEXT NOT NULL DEFAULT 'accepted',
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  occurred_on TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE UNIQUE INDEX IF NOT EXISTS evidence_items_source_unique
  ON evidence_items(source_type, source_ref);

CREATE INDEX IF NOT EXISTS evidence_items_user_date_idx
  ON evidence_items(user_id, occurred_on DESC);

CREATE INDEX IF NOT EXISTS evidence_items_user_status_idx
  ON evidence_items(user_id, status, evidence_type);

CREATE INDEX IF NOT EXISTS evidence_items_course_lesson_idx
  ON evidence_items(course_id, lesson_id);
