CREATE TABLE IF NOT EXISTS project_milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  template_id TEXT NOT NULL REFERENCES goal_templates(id),
  checkpoint_id TEXT NOT NULL REFERENCES goal_template_checkpoints(id),
  checkpoint_day INTEGER NOT NULL,
  artifact_url TEXT,
  evidence_text TEXT NOT NULL,
  evidence_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'accepted',
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  notes TEXT,
  submitted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE UNIQUE INDEX IF NOT EXISTS project_milestones_user_checkpoint_unique
  ON project_milestones(user_id, template_id, checkpoint_id);

CREATE INDEX IF NOT EXISTS project_milestones_user_status_idx
  ON project_milestones(user_id, status, checkpoint_day);
