CREATE TABLE IF NOT EXISTS quiz_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  enrollment_id BIGINT NOT NULL REFERENCES enrollments(id),
  lesson_id TEXT NOT NULL REFERENCES lessons(id),
  course_id TEXT NOT NULL REFERENCES courses(id),
  attempt_number INTEGER NOT NULL,
  is_revision INTEGER NOT NULL DEFAULT 0,
  question_count INTEGER NOT NULL,
  correct_count INTEGER NOT NULL,
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  passed INTEGER NOT NULL DEFAULT 0,
  answers_json TEXT NOT NULL DEFAULT '{}',
  submitted_on TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE UNIQUE INDEX IF NOT EXISTS quiz_attempts_user_lesson_attempt_unique
  ON quiz_attempts(user_id, lesson_id, attempt_number);

CREATE INDEX IF NOT EXISTS quiz_attempts_user_created_idx
  ON quiz_attempts(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS quiz_attempts_course_lesson_idx
  ON quiz_attempts(course_id, lesson_id);
