CREATE TABLE IF NOT EXISTS agent_lab_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  template_id TEXT NOT NULL REFERENCES goal_templates(id),
  builder_provider TEXT NOT NULL DEFAULT 'flowise',
  builder_project_ref TEXT,
  workflow_ref TEXT,
  workflow_export_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'draft',
  runtime_status TEXT NOT NULL DEFAULT 'not_tested',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS agent_lab_projects_user_template_provider_unique
  ON agent_lab_projects(user_id, template_id, builder_provider);

CREATE INDEX IF NOT EXISTS agent_lab_projects_user_status_idx
  ON agent_lab_projects(user_id, status);

CREATE INDEX IF NOT EXISTS agent_lab_projects_provider_status_idx
  ON agent_lab_projects(builder_provider, status);

CREATE TABLE IF NOT EXISTS agent_runtime_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  agent_project_id BIGINT NOT NULL REFERENCES agent_lab_projects(id),
  check_type TEXT NOT NULL DEFAULT 'manual_runtime',
  test_cases_json TEXT NOT NULL DEFAULT '[]',
  result_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'recorded',
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS agent_runtime_checks_project_created_idx
  ON agent_runtime_checks(agent_project_id, created_at);

CREATE INDEX IF NOT EXISTS agent_runtime_checks_user_status_idx
  ON agent_runtime_checks(user_id, status);
