CREATE TABLE IF NOT EXISTS knowledge_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type TEXT NOT NULL,
  title TEXT NOT NULL,
  source_url TEXT,
  canonical_ref TEXT NOT NULL,
  license TEXT,
  relevance TEXT NOT NULL DEFAULT 'unclassified',
  status TEXT NOT NULL DEFAULT 'pending_review',
  review_notes TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS knowledge_sources_canonical_ref_unique
  ON knowledge_sources(canonical_ref);

CREATE INDEX IF NOT EXISTS knowledge_sources_status_created_idx
  ON knowledge_sources(status, created_at);

CREATE INDEX IF NOT EXISTS knowledge_sources_type_status_idx
  ON knowledge_sources(source_type, status);
