CREATE TABLE IF NOT EXISTS course_content_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id TEXT NOT NULL REFERENCES courses(id),
  version TEXT NOT NULL,
  source_ref TEXT NOT NULL DEFAULT 'academy_seed',
  status TEXT NOT NULL DEFAULT 'draft',
  change_summary TEXT NOT NULL DEFAULT '',
  created_by TEXT,
  reviewed_by TEXT,
  reviewed_at TIMESTAMP,
  published_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS course_content_versions_course_version_unique
  ON course_content_versions(course_id, version);

CREATE INDEX IF NOT EXISTS course_content_versions_status_updated_idx
  ON course_content_versions(status, updated_at);

CREATE INDEX IF NOT EXISTS course_content_versions_course_status_idx
  ON course_content_versions(course_id, status);
