CREATE TABLE IF NOT EXISTS course_quality_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id TEXT NOT NULL REFERENCES courses(id),
  lesson_id TEXT REFERENCES lessons(id),
  content_version_id BIGINT REFERENCES course_content_versions(id),
  event_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'watch',
  status TEXT NOT NULL DEFAULT 'open',
  source_type TEXT NOT NULL,
  source_ref TEXT NOT NULL,
  metrics_json TEXT NOT NULL DEFAULT '{}',
  recommendation TEXT NOT NULL DEFAULT '',
  created_by TEXT,
  resolved_by TEXT,
  resolved_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS course_quality_events_source_unique
  ON course_quality_events(source_type, source_ref);

CREATE INDEX IF NOT EXISTS course_quality_events_status_severity_idx
  ON course_quality_events(status, severity, updated_at);

CREATE INDEX IF NOT EXISTS course_quality_events_course_lesson_idx
  ON course_quality_events(course_id, lesson_id);
