CREATE TABLE IF NOT EXISTS seed_user_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  note_type TEXT NOT NULL DEFAULT 'follow_up',
  completion_source TEXT,
  failure_reason TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  content TEXT NOT NULL,
  recorded_by TEXT,
  recorded_on DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS seed_user_notes_user_created_idx
  ON seed_user_notes(user_id, created_at);

CREATE INDEX IF NOT EXISTS seed_user_notes_type_status_idx
  ON seed_user_notes(note_type, status, created_at);

CREATE INDEX IF NOT EXISTS seed_user_notes_reason_idx
  ON seed_user_notes(failure_reason, created_at);
