CREATE TABLE IF NOT EXISTS competency_proof_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  user_id TEXT NOT NULL REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'active',
  snapshot_json TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP,
  revoked_at TIMESTAMP,
  last_viewed_at TIMESTAMP,
  view_count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS competency_proof_shares_token_idx
  ON competency_proof_shares(token);

CREATE INDEX IF NOT EXISTS competency_proof_shares_user_created_idx
  ON competency_proof_shares(user_id, created_at);
