import type { AppLocale } from "./i18n";

const zh = {
  title: "英语对话练习", intro: "把今天学到的表达说出来。练习后查看反馈，再试一次。", open: "开始对话练习", close: "收起对话", scene: "场景", level: "难度",
  scenes: ["自我介绍", "餐厅点单", "日常聊天"], levels: ["入门", "基础", "进阶"], start: "开始新对话", history: "最近练习", active: "继续练习", completed: "查看反馈", loading: "正在加载…",
  you: "你", partner: "AI 伙伴", draft: "你的回复", placeholder: "用英语回复，也可以先中英混说…", send: "发送", busy: "正在处理…", hint: "给我提示", hintNote: "试着套用这个表达：", listen: "朗读", stopAudio: "停止朗读", mic: "语音输入", stopMic: "结束录音", recording: "正在听，请说英语…", finish: "结束并查看反馈", minTurns: "至少回复 3 次后可查看反馈，每次练习最多 12 轮。", strength: "做得好的地方", corrections: "可以改进的表达", practice: "再说一次", again: "用这句话开始新练习", noCorrections: "这次没有需要特别修改的表达。", saved: "已保存到本课练习记录", boundary: "对话练习单独记录；完成本课仍需提交原有检查题。反馈依据文字，不评价发音。",
  privacy: "发送的文字会保存到 Academy 并交由 AI 处理。语音输入可能使用浏览器的在线识别服务；录音不上传到 Academy。识别后请检查文字再发送。",
  unsupported: "此浏览器暂不支持语音识别，请使用文字输入。", speechFailed: "未能识别语音，请检查麦克风权限或改用文字。", audioFailed: "当前设备无法朗读，可直接阅读文字。", noAi: "对话服务尚未配置，暂时可以查看历史练习。", readOnly: "本课当前只支持查看历史练习。", error: "暂时无法连接，请重试。", limit: "今天的练习用量已达上限，请明天继续。", conflict: "对话正在处理或已更新，请刷新练习记录后继续。", expired: "学习权限已到期，请到个人中心查看续期方式。", refresh: "刷新练习记录", service: "AI 暂时无法回复，你的输入已保留，可以重试。", turnLimit: "已完成 12 轮，请结束并查看反馈。",
};
type EnglishCopy = typeof zh;
const vi: EnglishCopy = {
  title: "Luyện hội thoại tiếng Anh", intro: "Dùng cách diễn đạt của bài học trong hội thoại và luyện lại sau phản hồi.", open: "Mở luyện hội thoại", close: "Thu gọn", scene: "Tình huống", level: "Trình độ", scenes: ["Giới thiệu bản thân", "Gọi món", "Trò chuyện hằng ngày"], levels: ["Mới bắt đầu", "Cơ bản", "Trung cấp"], start: "Hội thoại mới", history: "Buổi luyện gần đây", active: "Tiếp tục", completed: "Xem phản hồi", loading: "Đang tải…", you: "Bạn", partner: "Bạn luyện AI", draft: "Câu trả lời", placeholder: "Trả lời bằng tiếng Anh, có thể kết hợp tiếng mẹ đẻ…", send: "Gửi", busy: "Đang xử lý…", hint: "Gợi ý", hintNote: "Thử dùng mẫu câu này:", listen: "Nghe", stopAudio: "Dừng đọc", mic: "Nhập bằng giọng nói", stopMic: "Dừng ghi âm", recording: "Đang nghe tiếng Anh…", finish: "Kết thúc và xem phản hồi", minTurns: "Trả lời ít nhất 3 lần để nhận phản hồi; tối đa 12 lượt.", strength: "Điểm làm tốt", corrections: "Cách diễn đạt tốt hơn", practice: "Luyện nói lại", again: "Luyện câu này trong hội thoại mới", noCorrections: "Không có câu nào cần sửa đặc biệt.", saved: "Đã lưu vào lịch sử bài học", boundary: "Hội thoại được lưu riêng; vẫn cần nộp bài kiểm tra. Phản hồi dựa trên văn bản, không đánh giá phát âm.", privacy: "Văn bản gửi được lưu tại Academy và xử lý bằng AI. Nhận dạng giọng nói có thể dùng dịch vụ trực tuyến của trình duyệt; Academy không nhận bản ghi âm. Kiểm tra văn bản trước khi gửi.", unsupported: "Trình duyệt chưa hỗ trợ nhận dạng giọng nói. Hãy nhập văn bản.", speechFailed: "Không nhận dạng được. Kiểm tra quyền micro hoặc nhập văn bản.", audioFailed: "Thiết bị không đọc được. Bạn có thể đọc văn bản.", noAi: "Chưa cấu hình dịch vụ hội thoại. Bạn vẫn xem được lịch sử.", readOnly: "Hiện chỉ xem được lịch sử bài học này.", error: "Chưa kết nối được. Hãy thử lại.", limit: "Đã đạt giới hạn hôm nay. Hãy tiếp tục vào ngày mai.", conflict: "Hội thoại đang xử lý hoặc đã đổi. Hãy tải lại lịch sử.", expired: "Quyền học đã hết hạn. Xem gia hạn trong hồ sơ.", refresh: "Tải lại lịch sử", service: "AI chưa trả lời được. Nội dung nhập được giữ lại để thử lại.", turnLimit: "Đã đủ 12 lượt. Hãy kết thúc để xem phản hồi.",
};
const km: EnglishCopy = {
  title: "ហាត់សន្ទនាភាសាអង់គ្លេស", intro: "ប្រើឃ្លាពីមេរៀនថ្ងៃនេះ ហើយហាត់ឡើងវិញក្រោយមតិកែលម្អ។", open: "ចាប់ផ្ដើមហាត់សន្ទនា", close: "បិទផ្ទាំងសន្ទនា", scene: "ស្ថានភាព", level: "កម្រិត", scenes: ["ណែនាំខ្លួន", "កុម្ម៉ង់អាហារ", "សន្ទនាប្រចាំថ្ងៃ"], levels: ["អ្នកចាប់ផ្ដើម", "មូលដ្ឋាន", "មធ្យម"], start: "សន្ទនាថ្មី", history: "ការហាត់ថ្មីៗ", active: "បន្តហាត់", completed: "មើលមតិកែលម្អ", loading: "កំពុងផ្ទុក…", you: "អ្នក", partner: "ដៃគូ AI", draft: "ចម្លើយរបស់អ្នក", placeholder: "ឆ្លើយជាអង់គ្លេស អាចលាយភាសារបស់អ្នកបាន…", send: "ផ្ញើ", busy: "កំពុងដំណើរការ…", hint: "ជំនួយ", hintNote: "សាកប្រើឃ្លានេះ៖", listen: "ស្ដាប់", stopAudio: "ឈប់អាន", mic: "បញ្ចូលដោយសំឡេង", stopMic: "ឈប់ថត", recording: "កំពុងស្ដាប់ភាសាអង់គ្លេស…", finish: "បញ្ចប់ និងមើលមតិកែលម្អ", minTurns: "ឆ្លើយយ៉ាងតិច 3 ដង ដើម្បីទទួលមតិកែលម្អ។ អតិបរមា 12 ជុំ។", strength: "ចំណុចល្អ", corrections: "ឃ្លាដែលអាចកែលម្អ", practice: "និយាយម្ដងទៀត", again: "ហាត់ឃ្លានេះក្នុងសន្ទនាថ្មី", noCorrections: "មិនមានឃ្លាដែលត្រូវកែជាពិសេសទេ។", saved: "បានរក្សាទុកក្នុងប្រវត្តិមេរៀន", boundary: "ការសន្ទនារក្សាទុកដាច់ដោយឡែក។ នៅតែត្រូវបញ្ជូនតេស្តមេរៀន។ មតិផ្អែកលើអត្ថបទ មិនវាយតម្លៃការបញ្ចេញសំឡេងទេ។", privacy: "អត្ថបទដែលផ្ញើត្រូវបានរក្សាទុកនៅ Academy និងដំណើរការដោយ AI។ ការស្គាល់សំឡេងអាចប្រើសេវាអនឡាញរបស់កម្មវិធីរុករក។ Academy មិនទទួលការថតសំឡេងទេ។ ពិនិត្យអត្ថបទមុនផ្ញើ។", unsupported: "កម្មវិធីរុករកនេះមិនគាំទ្រការស្គាល់សំឡេងទេ។ សូមវាយអត្ថបទ។", speechFailed: "មិនអាចស្គាល់សំឡេង។ ពិនិត្យសិទ្ធិមីក្រូហ្វូន ឬវាយអត្ថបទ។", audioFailed: "ឧបករណ៍មិនអាចអានឱ្យស្ដាប់បាន។ សូមអានអត្ថបទ។", noAi: "សេវាសន្ទនាមិនទាន់បានកំណត់។ អាចមើលប្រវត្តិបាន។", readOnly: "អាចមើលតែប្រវត្តិមេរៀននេះ។", error: "មិនអាចភ្ជាប់បាន។ សូមព្យាយាមម្ដងទៀត។", limit: "ដល់កំណត់ប្រចាំថ្ងៃហើយ។ សូមបន្តថ្ងៃស្អែក។", conflict: "សន្ទនាកំពុងដំណើរការ ឬបានផ្លាស់ប្ដូរ។ សូមផ្ទុកប្រវត្តិឡើងវិញ។", expired: "សិទ្ធិរៀនផុតកំណត់។ មើលការបន្តនៅប្រវត្តិរូប។", refresh: "ផ្ទុកប្រវត្តិឡើងវិញ", service: "AI មិនអាចឆ្លើយបានឥឡូវនេះ។ អត្ថបទរបស់អ្នកត្រូវបានទុកសម្រាប់សាកម្ដងទៀត។", turnLimit: "គ្រប់ 12 ជុំហើយ។ សូមបញ្ចប់ដើម្បីមើលមតិកែលម្អ។",
};
const th: EnglishCopy = {
  title: "ฝึกสนทนาภาษาอังกฤษ", intro: "ลองใช้สำนวนจากบทเรียนวันนี้ แล้วฝึกซ้ำหลังรับคำแนะนำ", open: "เปิดฝึกสนทนา", close: "ย่อการสนทนา", scene: "สถานการณ์", level: "ระดับ", scenes: ["แนะนำตัว", "สั่งอาหาร", "สนทนาประจำวัน"], levels: ["เริ่มต้น", "พื้นฐาน", "ปานกลาง"], start: "เริ่มบทสนทนาใหม่", history: "การฝึกล่าสุด", active: "ฝึกต่อ", completed: "ดูคำแนะนำ", loading: "กำลังโหลด…", you: "คุณ", partner: "คู่ฝึก AI", draft: "คำตอบของคุณ", placeholder: "ตอบเป็นภาษาอังกฤษ หรือผสมภาษาแม่ก่อนได้…", send: "ส่ง", busy: "กำลังประมวลผล…", hint: "ขอคำใบ้", hintNote: "ลองใช้สำนวนนี้:", listen: "ฟัง", stopAudio: "หยุดอ่าน", mic: "ป้อนด้วยเสียง", stopMic: "หยุดบันทึก", recording: "กำลังฟังภาษาอังกฤษ…", finish: "จบและดูคำแนะนำ", minTurns: "ตอบอย่างน้อย 3 ครั้งเพื่อรับคำแนะนำ ฝึกได้สูงสุด 12 รอบ", strength: "สิ่งที่ทำได้ดี", corrections: "สำนวนที่ปรับปรุงได้", practice: "ลองพูดอีกครั้ง", again: "ฝึกประโยคนี้ในบทสนทนาใหม่", noCorrections: "ครั้งนี้ไม่มีสำนวนที่ต้องแก้เป็นพิเศษ", saved: "บันทึกในประวัติบทเรียนแล้ว", boundary: "บันทึกบทสนทนาแยกต่างหาก ยังต้องส่งแบบทดสอบเดิม คำแนะนำอิงข้อความ ไม่ประเมินการออกเสียง", privacy: "ข้อความที่ส่งจะบันทึกที่ Academy และประมวลผลด้วย AI การรู้จำเสียงอาจใช้บริการออนไลน์ของเบราว์เซอร์ Academy ไม่รับไฟล์บันทึกเสียง โปรดตรวจข้อความก่อนส่ง", unsupported: "เบราว์เซอร์นี้ไม่รองรับการรู้จำเสียง กรุณาพิมพ์ข้อความ", speechFailed: "ไม่สามารถรู้จำเสียงได้ ตรวจสิทธิ์ไมโครโฟนหรือพิมพ์ข้อความ", audioFailed: "อุปกรณ์นี้อ่านออกเสียงไม่ได้ สามารถอ่านข้อความได้", noAi: "ยังไม่ได้ตั้งค่าบริการสนทนา แต่ดูประวัติได้", readOnly: "ขณะนี้ดูได้เฉพาะประวัติบทเรียนนี้", error: "เชื่อมต่อไม่ได้ กรุณาลองใหม่", limit: "ถึงขีดจำกัดวันนี้แล้ว โปรดฝึกต่อพรุ่งนี้", conflict: "บทสนทนากำลังประมวลผลหรือเปลี่ยนแล้ว กรุณาโหลดประวัติใหม่", expired: "สิทธิ์เรียนหมดอายุ ดูการต่ออายุในโปรไฟล์", refresh: "โหลดประวัติใหม่", service: "AI ยังตอบไม่ได้ เก็บข้อความของคุณไว้ให้ลองส่งใหม่แล้ว", turnLimit: "ครบ 12 รอบแล้ว กรุณาจบเพื่อดูคำแนะนำ",
};
export function englishConversationCopy(locale: AppLocale) {
  const copy = ({ "zh-Hans": zh, vi, km, th })[locale];
  const colleague = { "zh-Hans": "同事沟通：确认任务", vi: "Đồng nghiệp: xác nhận công việc", km: "មិត្តរួមការងារ៖ បញ្ជាក់ភារកិច្ច", th: "เพื่อนร่วมงาน: ยืนยันงาน" }[locale];
  return { ...copy, scenes: [...copy.scenes, colleague] };
}
